import { Code, Megaphone, Linkedin, Github, InstagramIcon, MessageCircle, Rocket, Users, PenTool, MonitorSmartphone, Twitter } from 'lucide-react';
import { PlaceHolderImages } from './placeholder-images';

export const navLinks = [
    { href: '/#hero', labelKey: 'nav.home' },
    { href: '/#experience', labelKey: 'nav.experience' },
    { href: '/#work', labelKey: 'nav.work' },
    { href: '/#about', labelKey: 'nav.about' },
    { href: '/#contact', labelKey: 'nav.contact' },
];

export const services = [
    {
        titleKey: 'services.web.title',
        descriptionKey: 'services.web.description',
        icon: Code,
        featured: true,
        includesKeys: [
            'services.web.includes.frontend',
            'services.web.includes.backend',
            'services.web.includes.responsive',
            'services.web.includes.deploy',
        ],
    },
    {
        titleKey: 'services.ui.title',
        descriptionKey: 'services.ui.description',
        icon: PenTool,
        includesKeys: [
            'services.ui.includes.ui',
            'services.ui.includes.design',
            'services.ui.includes.performance',
            'services.ui.includes.accessibility',
        ],
    },
    {
        titleKey: 'services.maintenance.title',
        descriptionKey: 'services.maintenance.description',
        icon: Rocket,
        includesKeys: [
            'services.maintenance.includes.refactors',
            'services.maintenance.includes.bugs',
            'services.maintenance.includes.features',
            'services.maintenance.includes.performance',
        ],
    },
];

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

export const portfolioProjects: PortfolioProject[] = [
    {
        id: '1', // Ayepsicope
        titleKey: 'projects.7.title',
        descriptionKey: 'projects.7.description',
        tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
        image: getImage('work-5'),
        liveUrl: 'https://ayepsicope.vercel.app/',
        details: {
            nameKey: 'projects.7.details.name',
            summaryKey: 'projects.7.details.summary',
            stackKey: 'projects.7.details.stack',
            statusKey: 'projects.7.details.status',
            typeKey: 'projects.7.details.type',
            contextKey: 'projects.7.details.context',
            objectiveKey: 'projects.7.details.objective',
            objectiveItemsKey: 'projects.7.details.objective.items',
            processKey: 'projects.7.details.process',
            processStepsKey: 'projects.7.details.process.steps',
            resultKey: 'projects.7.details.result',
            resultItemsKey: 'projects.7.details.result.items',
            roleKey: 'projects.7.details.role',
            responsibilitiesKey: 'projects.7.details.responsibilities',
            technologiesKey: 'projects.7.details.technologies',
            feedbackKey: 'projects.7.details.feedback',
        },
    },
    {
        id: '2', // Roma
        titleKey: 'projects.1.title',
        descriptionKey: 'projects.1.description',
        tags: ['HTML', 'CSS', 'JavaScript'],
        image: getImage('work-1'),
        liveUrl: 'https://romamasajes.com/',
        details: {
            nameKey: 'projects.1.details.name',
            summaryKey: 'projects.1.details.summary',
            stackKey: 'projects.1.details.stack',
            statusKey: 'projects.1.details.status',
            typeKey: 'projects.1.details.type',
            contextKey: 'projects.1.details.context',
            objectiveKey: 'projects.1.details.objective',
            objectiveItemsKey: 'projects.1.details.objective.items',
            processKey: 'projects.1.details.process',
            processStepsKey: 'projects.1.details.process.steps',
            resultKey: 'projects.1.details.result',
            resultItemsKey: 'projects.1.details.result.items',
            roleKey: 'projects.1.details.role',
            responsibilitiesKey: 'projects.1.details.responsibilities',
            technologiesKey: 'projects.1.details.technologies',
            feedbackKey: 'projects.1.details.feedback',
        },
    },
    {
        id: '3', // Campus Desafíos
        titleKey: 'projects.10.title',
        descriptionKey: 'projects.10.description',
        tags: ['Vue.js', 'Laravel', 'PostgreSQL', 'Tailwind'],
        image: getImage('work-9'),
        liveUrl: 'https://campus.marianacasella.com/desafio-express',
        details: {
            nameKey: 'projects.10.details.name',
            summaryKey: 'projects.10.details.summary',
            stackKey: 'projects.10.details.stack',
            statusKey: 'projects.10.details.status',
            typeKey: 'projects.10.details.type',
            contextKey: 'projects.10.details.context',
            objectiveKey: 'projects.10.details.objective',
            objectiveItemsKey: 'projects.10.details.objective.items',
            processKey: 'projects.10.details.process',
            processStepsKey: 'projects.10.details.process.steps',
            resultKey: 'projects.10.details.result',
            resultItemsKey: 'projects.10.details.result.items',
            roleKey: 'projects.10.details.role',
            responsibilitiesKey: 'projects.10.details.responsibilities',
            technologiesKey: 'projects.10.details.technologies',
            feedbackKey: 'projects.10.details.feedback',
        },
    },
    {
        id: '4', // Stardew Guide
        titleKey: 'projects.4.title',
        descriptionKey: 'projects.4.description',
        tags: ['Next.js', 'React', 'TypeScript', 'Zustand'],
        image: getImage('work-4'),
        liveUrl: 'https://stardew-guide.vercel.app/',
        details: {
            nameKey: 'projects.4.details.name',
            summaryKey: 'projects.4.details.summary',
            stackKey: 'projects.4.details.stack',
            statusKey: 'projects.4.details.status',
            typeKey: 'projects.4.details.type',
            contextKey: 'projects.4.details.context',
            objectiveKey: 'projects.4.details.objective',
            objectiveItemsKey: 'projects.4.details.objective.items',
            processKey: 'projects.4.details.process',
            processStepsKey: 'projects.4.details.process.steps',
            resultKey: 'projects.4.details.result',
            resultItemsKey: 'projects.4.details.result.items',
            roleKey: 'projects.4.details.role',
            responsibilitiesKey: 'projects.4.details.responsibilities',
            technologiesKey: 'projects.4.details.technologies',
            feedbackKey: 'projects.4.details.feedback',
        },
    },
    {
        id: '5', // Command Center
        titleKey: 'projects.8.title',
        descriptionKey: 'projects.8.description',
        tags: ['JavaScript', 'Vite', 'Tailwind'],
        image: getImage('work-7'),
        liveUrl: 'https://commandcenterdev.netlify.app/',
        githubUrl: 'https://github.com/CinloDev/command',
        details: {
            nameKey: 'projects.8.details.name',
            summaryKey: 'projects.8.details.summary',
            stackKey: 'projects.8.details.stack',
            statusKey: 'projects.8.details.status',
            typeKey: 'projects.8.details.type',
            contextKey: 'projects.8.details.context',
            objectiveKey: 'projects.8.details.objective',
            objectiveItemsKey: 'projects.8.details.objective.items',
            processKey: 'projects.8.details.process',
            processStepsKey: 'projects.8.details.process.steps',
            resultKey: 'projects.8.details.result',
            resultItemsKey: 'projects.8.details.result.items',
            roleKey: 'projects.8.details.role',
            responsibilitiesKey: 'projects.8.details.responsibilities',
            technologiesKey: 'projects.8.details.technologies',
            feedbackKey: 'projects.8.details.feedback',
        },
    },
    {
        id: '6', // MailQuark
        titleKey: 'projects.9.title',
        descriptionKey: 'projects.9.description',
        tags: ['Next.js', 'TypeScript', 'SMTP', 'Vanilla CSS'],
        image: getImage('work-8'),
        liveUrl: 'https://email-test-public.vercel.app/',
        githubUrl: 'https://github.com/CinloDev/email_test_public',
        details: {
            nameKey: 'projects.9.details.name',
            summaryKey: 'projects.9.details.summary',
            stackKey: 'projects.9.details.stack',
            statusKey: 'projects.9.details.status',
            typeKey: 'projects.9.details.type',
            contextKey: 'projects.9.details.context',
            objectiveKey: 'projects.9.details.objective',
            objectiveItemsKey: 'projects.9.details.objective.items',
            processKey: 'projects.9.details.process',
            processStepsKey: 'projects.9.details.process.steps',
            resultKey: 'projects.9.details.result',
            resultItemsKey: 'projects.9.details.result.items',
            roleKey: 'projects.9.details.role',
            responsibilitiesKey: 'projects.9.details.responsibilities',
            technologiesKey: 'projects.9.details.technologies',
            feedbackKey: 'projects.9.details.feedback',
        },
    },
    {
        id: '7', // API REST
        titleKey: 'projects.2.title',
        descriptionKey: 'projects.2.description',
        tags: ['JavaScript', 'Node.js', 'Express'],
        image: getImage('work-2'),
        liveUrl: 'https://cinlodev.github.io/asincronismo-js-practico-platzi/',
        githubUrl: 'https://github.com/CinloDev/api-rest-js-practico',
        details: {
            nameKey: 'projects.2.details.name',
            summaryKey: 'projects.2.details.summary',
            stackKey: 'projects.2.details.stack',
            statusKey: 'projects.2.details.status',
            typeKey: 'projects.2.details.type',
            contextKey: 'projects.2.details.context',
            objectiveKey: 'projects.2.details.objective',
            objectiveItemsKey: 'projects.2.details.objective.items',
            processKey: 'projects.2.details.process',
            processStepsKey: 'projects.2.details.process.steps',
            resultKey: 'projects.2.details.result',
            resultItemsKey: 'projects.2.details.result.items',
            roleKey: 'projects.2.details.role',
            responsibilitiesKey: 'projects.2.details.responsibilities',
            technologiesKey: 'projects.2.details.technologies',
            feedbackKey: 'projects.2.details.feedback',
        },
    },
    {
        id: '8', // Travel Landing
        titleKey: 'projects.3.title',
        descriptionKey: 'projects.3.description',
        tags: ['HTML', 'Tailwind CSS'],
        image: getImage('work-3'),
        liveUrl: 'https://cinlodev.github.io/travel-landing-tailwind/',
        githubUrl: 'https://github.com/CinloDev/travel-tailwind',
        details: {
            nameKey: 'projects.3.details.name',
            summaryKey: 'projects.3.details.summary',
            stackKey: 'projects.3.details.stack',
            statusKey: 'projects.3.details.status',
            typeKey: 'projects.3.details.type',
            contextKey: 'projects.3.details.context',
            objectiveKey: 'projects.3.details.objective',
            objectiveItemsKey: 'projects.3.details.objective.items',
            processKey: 'projects.3.details.process',
            processStepsKey: 'projects.3.details.process.steps',
            resultKey: 'projects.3.details.result',
            resultItemsKey: 'projects.3.details.result.items',
            roleKey: 'projects.3.details.role',
            responsibilitiesKey: 'projects.3.details.responsibilities',
            technologiesKey: 'projects.3.details.technologies',
            feedbackKey: 'projects.3.details.feedback',
        },
    },
    {
        id: '9', // Portfolio Astro
        titleKey: 'projects.6.title',
        descriptionKey: 'projects.6.description',
        tags: ['Astro', 'Tailwind CSS', 'TypeScript'],
        image: getImage('work-6'),
        liveUrl: 'https://cinlodev.github.io/cinlo-portfolio/',
        githubUrl: 'https://github.com/CinloDev/cinlo-portfolio',
        details: {
            nameKey: 'projects.6.details.name',
            summaryKey: 'projects.6.details.summary',
            stackKey: 'projects.6.details.stack',
            statusKey: 'projects.6.details.status',
            typeKey: 'projects.6.details.type',
            contextKey: 'projects.6.details.context',
            objectiveKey: 'projects.6.details.objective',
            objectiveItemsKey: 'projects.6.details.objective.items',
            processKey: 'projects.6.details.process',
            processStepsKey: 'projects.6.details.process.steps',
            resultKey: 'projects.6.details.result',
            resultItemsKey: 'projects.6.details.result.items',
            roleKey: 'projects.6.details.role',
            responsibilitiesKey: 'projects.6.details.responsibilities',
            technologiesKey: 'projects.6.details.technologies',
            feedbackKey: 'projects.6.details.feedback',
        },
    },
];

export const testimonials = [
    {
        quoteKey: 'testimonials.0.quote',
        authorKey: 'testimonials.0.author',
        companyKey: 'testimonials.0.company',
        avatar: './images/testimonial-aye.jpg',
    },
    {
        quoteKey: 'testimonials.1.quote',
        authorKey: 'testimonials.1.author',
        companyKey: 'testimonials.1.company',
        avatar: 'https://plus.unsplash.com/premium_photo-1681493353999-a3eea8b95e1d?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
        quoteKey: 'testimonials.2.quote',
        authorKey: 'testimonials.2.author',
        companyKey: 'testimonials.2.company',
        avatar: 'https://plus.unsplash.com/premium_photo-1702598904442-de1d96570fa8?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
        quoteKey: 'testimonials.3.quote',
        authorKey: 'testimonials.3.author',
        companyKey: 'testimonials.3.company',
        avatar: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
        quoteKey: 'testimonials.4.quote',
        authorKey: 'testimonials.4.author',
        companyKey: 'testimonials.4.company',
        avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
];

export const aboutMe = {
    descriptionKey: 'about.description',
    image: getImage('about-me'),
};

export const skillsSection = {
    titleKey: 'skills.title',
    introKey: 'skills.intro',
    columns: [
        {
            titleKey: 'skills.columns.frontend.title',
            items: [
                { nameKey: 'skills.columns.frontend.items.react', levelKey: 'skills.levels.proficient' },
                { nameKey: 'skills.columns.frontend.items.next', levelKey: 'skills.levels.proficient' },
                { nameKey: 'skills.columns.frontend.items.js', levelKey: 'skills.levels.proficient' },
                { nameKey: 'skills.columns.frontend.items.tailwind', levelKey: 'skills.levels.proficient' },
                { nameKey: 'skills.columns.frontend.items.htmlcss', levelKey: 'skills.levels.proficient' },
            ],
        },
        {
            titleKey: 'skills.columns.backend.title',
            items: [
                { nameKey: 'skills.columns.backend.items.node', levelKey: 'skills.levels.working' },
                { nameKey: 'skills.columns.backend.items.apis', levelKey: 'skills.levels.working' },
                { nameKey: 'skills.columns.backend.items.auth', levelKey: 'skills.levels.working' },
                { nameKey: 'skills.columns.backend.items.db', levelKey: 'skills.levels.working' },
            ],
        },
        {
            titleKey: 'skills.columns.tools.title',
            items: [
                { nameKey: 'skills.columns.tools.items.git', levelKey: 'skills.levels.proficient' },
                { nameKey: 'skills.columns.tools.items.npm', levelKey: 'skills.levels.proficient' },
                { nameKey: 'skills.columns.tools.items.vercel', levelKey: 'skills.levels.working' },
                { nameKey: 'skills.columns.tools.items.figma', levelKey: 'skills.levels.familiar' },
            ],
        },
    ],
    levelsKeys: {
        proficient: 'skills.levels.proficient',
        working: 'skills.levels.working',
        familiar: 'skills.levels.familiar',
    },
};

export const socialLinks = [
    {
        name: 'LinkedIn',
        url: 'https://www.linkedin.com/in/cinlodev/',
        icon: Linkedin,
    },
    {
        name: 'GitHub',
        url: 'https://github.com/CinloDev',
        icon: Github,
    },
    {
        name: 'Twitter',
        url: 'https://x.com/CinloDev',
        icon: Twitter,
    },
    {
        name: 'Instagram',
        url: 'https://www.instagram.com/cinlodev/',
        icon: InstagramIcon,
    }
];
